// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAdvisor.Data;

#nullable disable

namespace StudentAdvisor.Migrations.AppDbcontext2Migrations
{
    [DbContext(typeof(AppDbcontext2))]
    partial class AppDbcontext2ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StudentAdvisor.Models.Student", b =>
                {
                    b.Property<ushort>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("StudentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ushort>("StudyId")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("StudentId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("StudentAdvisor.Models.Study", b =>
                {
                    b.Property<ushort>("StudyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("StudyId"));

                    b.Property<ushort>("StudentId")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("programTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StudyId");

                    b.ToTable("Study", (string)null);
                });

            modelBuilder.Entity("StudentStudy", b =>
                {
                    b.Property<ushort>("StudentsStudentId")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("StudiesStudyId")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("StudentsStudentId", "StudiesStudyId");

                    b.HasIndex("StudiesStudyId");

                    b.ToTable("StudentStudy");
                });

            modelBuilder.Entity("StudentStudy", b =>
                {
                    b.HasOne("StudentAdvisor.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentAdvisor.Models.Study", null)
                        .WithMany()
                        .HasForeignKey("StudiesStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
